emory-libraries/Pattern-Library

source/_data/listitems.json

Replace the jive and hong kong phooey placeholder text for something less offensive.

Changes tvipsum text for something less offensive

---

README.md

Updated README with install and generate instructions.

Add install and generate steps to README

---

package.json

Previously forgot to use --save flag when installing autoprefixer as dependency

adds autoprefixer to package.json

---

source/_patterns/molecules/10-text/90-copyright@inprogress.mustache

modifies script to properly insert copyright year via .textContent method

footer-copyright

---

source/css/scss/pattern-specific/_lead-paragraph.scss

Replaces font stack with variable

---

source/css/scss/base/_typography.scss

Added style to links:
- text-decoration-skip: ink

Link text decoration skip

---

Gruntfile.js
README.md

Fixes the grunt watch loop bug.

Grunt watch loop fix

---

source/js/patternlab.js

Fixes temporary show/hide issue with expired alerts, and updates all alerts to use an event-driven system.

Updated alerts to use events

---

.gitignore
Gruntfile.js
README.md
package.json

Adds deploy task to 'grunt release'
You should probably comment out the git tag task in Gruntfile.js when testing.

Grunt deploy

---

source/scss/core/_tables.scss

Fixes bordered table style typo

---

source/_patterns/30-organisms/10-containers/40-footer.mustache
source/scss/core/_footer.scss

Changes selector for footer

---

src/_patterns/50-organisms/intros/intro~text.css
src/_patterns/50-organisms/sections/main.css
src/_patterns/50-organisms/sections/main.hbs
src/_patterns/60-templates/generic/info.hbs
src/_patterns/60-templates/research-help/research-help.css
src/_patterns/60-templates/research-help/research-help.hbs
src/scss/vends/emory-libraries/patterns/50-organisms/_section-main.scss
src/scss/vends/emory-libraries/patterns/50-organisms/intro/_structure.scss
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_skin.scss
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_structure.scss
src/scss/vends/emory-libraries/patterns/60-templates/_research-help.scss
src/scss/vends/emory-libraries/patterns/60-templates/research-help/_skin.scss
src/scss/vends/emory-libraries/patterns/60-templates/research-help/_structure.scss
src/scss/vends/emory-libraries/utils/_functions.scss
src/scss/vends/emory-libraries/utils/functions/_selector.scss

This applies fixes for `organisms-main` to the necessary patterns.

Applies fixes for `organisms-main`

---

pattern-status.json
src/_extensions/helpers/patch.js
src/_patterns/40-compounds/lists/sidebar-list.css
src/_patterns/40-compounds/lists/sidebar-list.hbs
src/_patterns/50-organisms/intros/intro~bio.hbs
src/_patterns/50-organisms/intros/intro~text.css
src/_patterns/50-organisms/sections/main.css
src/_patterns/50-organisms/sections/main.hbs
src/_patterns/60-templates/staff/bio.css
src/_patterns/60-templates/staff/bio.hbs
src/_patterns/60-templates/staff/bio.json
src/_patterns/60-templates/staff/bio.md
src/_patterns/60-templates/staff/bio.scss
src/_patterns/60-templates/staff/staff-directory.hbs
src/_patterns/60-templates/staff/subject-librarian-directory.hbs
src/scss/patterns/__master.scss
src/scss/vends/emory-libraries/patterns/40-compounds/sidebar-list/_structure.scss
src/scss/vends/emory-libraries/patterns/50-organisms/intro/_structure.scss
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_skin.scss
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_structure.scss
src/scss/vends/emory-libraries/patterns/60-templates/_bio.scss
src/scss/vends/emory-libraries/patterns/60-templates/bio/_skin.scss
src/scss/vends/emory-libraries/patterns/60-templates/bio/_structure.scss
src/scss/vends/emory-libraries/patterns/__master.scss

This creates the `templates-bio` pattern. Related #169.

Creates pattern `templates-bio`

---

pattern-status.json
src/_data/breadcrumbs.json
src/_patterns/30-molecules/breadcrumbs.md
src/_patterns/30-molecules/breadcrumbs/breadcrumbs.css
src/_patterns/30-molecules/breadcrumbs/breadcrumbs.hbs
src/_patterns/30-molecules/breadcrumbs/breadcrumbs.json
src/_patterns/30-molecules/breadcrumbs/breadcrumbs.md
src/_patterns/30-molecules/breadcrumbs/breadcrumbs.scss
src/_patterns/50-organisms/sections/main.css
src/_patterns/50-organisms/sections/main.hbs
src/scss/patterns/__master.scss
src/scss/vends/emory-libraries/patterns/30-molecules/_breadcrumbs.scss
src/scss/vends/emory-libraries/patterns/30-molecules/breadcrumbs/_skin.scss
src/scss/vends/emory-libraries/patterns/30-molecules/breadcrumbs/_structure.scss
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_skin.scss
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_structure.scss
src/scss/vends/emory-libraries/patterns/__master.scss

This adds patterns and styles for `molecules-breadcrumbs`.

Adds patterns and styles for molecule-breadcrumbs

---

package-lock.json
package.json
pattern-status.json
src/_extensions/helpers/string.js
src/_patterns/30-molecules/modules/slide.css
src/_patterns/40-compounds/modules/slider.css
src/_patterns/40-compounds/modules/slider.hbs
src/_patterns/40-compounds/modules/slider.js
src/_patterns/40-compounds/modules/slider.json
src/_patterns/40-compounds/modules/slider.md
src/_patterns/40-compounds/modules/slider.scss
src/js/_foot.index.js
src/js/_head.index.js
src/scss/patternlab.scss
src/scss/patterns/__master.scss
src/scss/vends/emory-libraries/patterns/30-molecules/_breadcrumbs.scss
src/scss/vends/emory-libraries/patterns/30-molecules/slide/_skin.scss
src/scss/vends/emory-libraries/patterns/30-molecules/slide/_structure.scss
src/scss/vends/emory-libraries/patterns/40-compounds/_grouping-files.scss
src/scss/vends/emory-libraries/patterns/40-compounds/_slider.scss
src/scss/vends/emory-libraries/patterns/40-compounds/slider/_skin.scss
src/scss/vends/emory-libraries/patterns/40-compounds/slider/_structure.scss
src/scss/vends/emory-libraries/patterns/50-organisms/_flow-content-boxes.scss
src/scss/vends/emory-libraries/patterns/__master.scss

This creates the pattern for `compounds-slider` and optimizes it for mobile (swipe events) and accessibility (keyboard events). This closes #214.

Creates pattern `compounds-slider`

---

pattern-status.json
src/_patterns/40-compounds/cards/cards.hbs
src/_patterns/50-organisms/sections/main.css
src/_patterns/60-templates/research-help/research-help-directory.css
src/_patterns/60-templates/research-help/research-help-directory.hbs
src/_patterns/60-templates/research-help/research-help-directory.json
src/_patterns/60-templates/research-help/research-help-directory.md
src/_patterns/60-templates/research-help/research-help-directory.scss
src/scss/patterns/__master.scss
src/scss/vends/emory-libraries/patterns/30-molecules/_breadcrumbs.scss
src/scss/vends/emory-libraries/patterns/40-compounds/_grouping-files.scss
src/scss/vends/emory-libraries/patterns/50-organisms/_flow-content-boxes.scss
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_structure.scss
src/scss/vends/emory-libraries/patterns/60-templates/_research-help-directory.scss
src/scss/vends/emory-libraries/patterns/60-templates/research-help-directory/_skin.scss
src/scss/vends/emory-libraries/patterns/60-templates/research-help-directory/_structure.scss
src/scss/vends/emory-libraries/patterns/__master.scss

This creates the `templates-research-help-directory` pattern, and closes #154.

Creates pattern `templates-research-help-directory`

---

pattern-status.json
src/_patterns/20-atoms/buttons/11-nav-button~main.css
src/_patterns/20-atoms/buttons/11-nav-button~main.hbs
src/_patterns/20-atoms/buttons/21-subnav-button~main.css
src/_patterns/40-compounds/navigation/nav-menu~main.css
src/_patterns/40-compounds/navigation/nav-menu~main.hbs
src/_patterns/40-compounds/navigation/nav-menu~main.js
src/_patterns/40-compounds/navigation/nav-menu~main.json
src/_patterns/40-compounds/navigation/nav-menu~main.md
src/_patterns/40-compounds/navigation/nav-menu~main.scss
src/_patterns/40-compounds/navigation/nav-menu~utility.hbs
src/_patterns/40-compounds/navigation/subnav-menu~main.css
src/_patterns/40-compounds/navigation/subnav-menu~main.hbs
src/_patterns/40-compounds/navigation/subnav-menu~main.json
src/scss/patterns/__master.scss
src/scss/vends/emory-libraries/patterns/20-atoms/nav-button/_skin.scss
src/scss/vends/emory-libraries/patterns/20-atoms/nav-button/_structure.scss
src/scss/vends/emory-libraries/patterns/20-atoms/subnav-button/_structure.scss
src/scss/vends/emory-libraries/patterns/40-compounds/_nav-menu-main.scss
src/scss/vends/emory-libraries/patterns/40-compounds/nav-menu-main/_skin.scss
src/scss/vends/emory-libraries/patterns/40-compounds/nav-menu-main/_structure.scss
src/scss/vends/emory-libraries/patterns/40-compounds/subnav-menu-main/_structure.scss
src/scss/vends/emory-libraries/patterns/__master.scss
src/scss/vends/emory-libraries/utils/mixins/_breakpoints.scss

This creates the `compounds-nav-menu-main` pattern. Closes #162.

Creates pattern `compounds-nav-menu-main`

---

src/_patterns/30-molecules/cards/card~listing.hbs
src/_patterns/50-organisms/intros/intro~hero.hbs

Fixes exhibition and gallery templates

---

src/_patterns/40-compounds/blocks/blocks.hbs
src/_patterns/40-compounds/cards/cards.hbs
src/_patterns/50-organisms/intros/intro~alt-text.hbs
src/_patterns/50-organisms/sections/main.css
src/_patterns/50-organisms/sections/main.hbs
src/_patterns/60-templates/exhibitions/gallery.hbs
src/_patterns/60-templates/generic/info.css
src/_patterns/60-templates/generic/info.hbs
src/_patterns/60-templates/generic/info.json
src/_patterns/60-templates/materials/material.hbs
src/_patterns/60-templates/materials/material.json
src/_patterns/60-templates/research-help/research-help.hbs
src/_patterns/60-templates/research-help/research-help.json
src/_patterns/60-templates/tools/tool.hbs
src/scss/vends/emory-libraries/patterns/50-organisms/section-main/_structure.scss
src/scss/vends/emory-libraries/patterns/60-templates/info/_structure.scss

This creates/modifies the `templates-research-help` pattern. Closes #166.

Creates pattern `templates-research-help`

---

package-lock.json
pattern-status.json
src/_patterns/30-molecules/branding/social-media.css
src/_patterns/30-molecules/branding/social-media.hbs
src/_patterns/30-molecules/branding/social-media.json
src/_patterns/30-molecules/branding/social-media.md
src/_patterns/30-molecules/branding/social-media.scss
src/scss/patterns/__master.scss
src/scss/vends/emory-libraries/patterns/30-molecules/_social-media.scss
src/scss/vends/emory-libraries/patterns/30-molecules/social-media/_skin.scss
src/scss/vends/emory-libraries/patterns/30-molecules/social-media/_structure.scss
src/scss/vends/emory-libraries/patterns/__master.scss

This creates the `molecules-social-media` pattern. Related #159.

Creates pattern `molecules-social-media`

---

src/_patterns/30-molecules/branding/branding~footer.js
src/_patterns/30-molecules/branding/branding~footer.json
src/_patterns/30-molecules/branding/branding~header.json
src/_patterns/50-organisms/navigation/footer.json

This fixes the issue of `//` being added to URLs without protocols.

Fix for footer location urls

---

src/_data/fixtures.json
src/_patterns/20-atoms/buttons/13-nav-button~flyout.json
src/_patterns/30-molecules/branding/branding~header.json
src/_patterns/40-compounds/navigation/nav-menu~utility.json
src/_patterns/50-organisms/navigation/header.json
src/_patterns/50-organisms/navigation/nav-bar~main.json

- Fixes mobile nav icon links to be actual links due to href values with empty strings.
- Fixes additional location list URLs without protocols in other patterns.

Fix for mobile nav icon links and locations list urls

---

src/_patterns/40-compounds/navigation/nav-menu~main.json
src/_patterns/50-organisms/navigation/nav-bar~main.json

Adds `href` values for mobile in...
- main nav compound, and
- nav bar organism.

Adds URL values for icons in mobile nav

---

src/_patterns/50-organisms/hours/hours~regular.json
src/_patterns/60-templates/hours/hours.json

Changes hours data to better demonstrate changes of semester hours per location.

Changes hours data files to reflect differences between semesters

---

src/php/proxy.php

creates a `isValidURL` function that uses a regex to determine whether or not the URL is a URL

ensures urls entered are urls

---

src/_patterns/50-organisms/navigation/search-menu.json

- src/_patterns/50-organisms/navigation/search-menu.json: adds the option of Digital Collections to the main library page.

Adds Digital Collections to main search menu. (#651)
